# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://robotcator.github.io/
baseurl: /sustain/
title: robotcator
author: robotcator
description: Personal Blog and Resume
avatar: profile.jpg
email: problemset@163.com
github: robotcator # username
twitter: robotcator
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username

tel_full: tel:0xffffff
google_maps: 'https://www.google.co.uk/maps/place/Hubei,+China'
address:
  city: Wuhan
  province: Hubei
  country: China

website: robotcator.github.io

google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
